FROM ubuntu:20.04

# Install tools needed for development
RUN apt update && \
    apt upgrade --yes && \
    apt install --yes build-essential git libssl-dev m4 python3-pip

# Copy needed source
RUN mkdir /src
ADD CMakeLists.txt FBGenCMakeBuildInfo.cmake ThriftLibrary.cmake /src/
COPY build /src/build
COPY openr/py/openr/ /src/openr
COPY openr/py/setup.py /src/openr

# Install `breeze` OpenR CLI
RUN cd /src && build/build_breeze.sh

# Cleanup all we can to keep container as lean as possible
RUN apt remove --yes build-essential git libssl-dev m4 && \
    apt autoremove --yes && \
    rm -rf /src /tmp/* /var/lib/apt/lists/*

CMD ["breeze --help"]
